import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import { mdsvex, escapeSvelte } from 'mdsvex';
import { createHighlighter } from 'shiki';
import rehypeSlug from 'rehype-slug';
import { existsSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const staticDir = resolve(__dirname, 'static');
const allowMermaidTextFallback =
	process.env.NODE_ENV !== 'production' || process.env.MERMAID_PRERENDER === 'optional';

// Load image dimensions manifest (generated by scripts/optimize-images.mts)
let imageDimensions = {};
const dimensionsPath = resolve(staticDir, 'images/posts/dimensions.json');
try {
	imageDimensions = JSON.parse(readFileSync(dimensionsPath, 'utf-8'));
} catch {
	// dimensions.json may not exist yet on first build
}

const theme = 'github-dark';
const highlighter = await createHighlighter({
	themes: [theme],
	langs: ['javascript', 'typescript', 'python', 'r', 'bash', 'html', 'css', 'json', 'yaml', 'toml', 'haskell', 'go', 'rust', 'markdown', 'shellscript', 'sql', 'nix', 'c', 'cpp', 'zig']
});

function escapeHtml(value) {
	return value
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;');
}

function extractNodeText(node) {
	if (!node) return '';
	if (node.type === 'text') return node.value || '';
	if (!node.children) return '';
	return node.children.map(extractNodeText).join('');
}

function findFirstImage(node) {
	if (!node) return null;
	if (node.type === 'element' && node.tagName === 'img') return node;
	if (!node.children) return null;

	for (const child of node.children) {
		const image = findFirstImage(child);
		if (image) return image;
	}

	return null;
}

function normalizeImageLabel(imageNode) {
	const alt = typeof imageNode?.properties?.alt === 'string' ? imageNode.properties.alt.trim() : '';
	if (alt) return alt;

	const src = typeof imageNode?.properties?.src === 'string' ? imageNode.properties.src : '';
	if (!src) return 'image';

	const filename = src.split('/').pop() || 'image';
	const stem = filename.replace(/\.[^.]+$/, '');
	if (!stem) return 'image';

	return stem
		.replace(/[_-]+/g, ' ')
		.replace(/\s+/g, ' ')
		.trim();
}

function visitNodes(node, parent, visitor) {
	visitor(node, parent);
	if (node.children) {
		for (const child of [...node.children]) {
			visitNodes(child, node, visitor);
		}
	}
}

/** @type {import('mdsvex').MdsvexOptions} */
const mdsvexOptions = {
	extensions: ['.md', '.svx'],
	highlight: {
		highlighter: async (code, lang) => {
			// Intercept mermaid code blocks — inline pre-rendered SVG from .mermaid-cache/
			if (lang === 'mermaid') {
				const trimmed = code.trim();
				const hash = createHash('sha256').update(trimmed).digest('hex').slice(0, 16);
				const svgPath = resolve(__dirname, '.mermaid-cache', `${hash}.svg`);
				if (existsSync(svgPath)) {
					const svg = readFileSync(svgPath, 'utf-8')
						.replace(/\{/g, '&#123;').replace(/\}/g, '&#125;');
					return `<div class="mermaid-diagram my-6 not-prose" role="figure" aria-label="Mermaid diagram">${svg}</div>`;
				}
				if (allowMermaidTextFallback) {
					return `<pre class="mermaid-diagram my-6 not-prose overflow-x-auto rounded-xl p-4"><code>${escapeHtml(trimmed)}</code></pre>`;
				}
				throw new Error(
					`Missing Mermaid prerender cache for ${hash}. Run the prebuild pipeline before shipping blog content with Mermaid diagrams.`
				);
			}
			const html = escapeSvelte(
				highlighter.codeToHtml(code, { lang: lang || 'text', theme })
			);
			return `{@html \`${html}\`}`;
		}
	},
	rehypePlugins: [
		// Auto-assign id="..." to headings so in-page anchor links
		// (Index blocks at the top of a post) can target them. Uses
		// github-slugger semantics: lowercase, whitespace -> '-',
		// non-word chars stripped. Em-dash + spaces collapses to '--'.
		rehypeSlug,
		// Wrap local post images in <picture> with WebP source for responsive loading
		() => (tree) => {
			const visitImg = (node, parent) => {
				if (
					node.type === 'element' &&
					node.tagName === 'img' &&
					node.properties?.src &&
					typeof node.properties.src === 'string' &&
					node.properties.src.startsWith('/images/posts/')
				) {
					const src = node.properties.src;
					const ext = src.substring(src.lastIndexOf('.'));
					const basePath = src.substring(0, src.lastIndexOf('.'));
					const webpSrc = basePath + '.webp';
					const webpFile = resolve(staticDir, webpSrc.slice(1)); // remove leading /

					// Add lazy loading and async decoding to the img
					node.properties.loading = 'lazy';
					node.properties.decoding = 'async';

					// Add width/height from dimensions manifest to prevent CLS
					const dims = imageDimensions[src];
					if (dims && dims.width && dims.height) {
						node.properties.width = dims.width;
						node.properties.height = dims.height;
					}

					// Only wrap in <picture> if a .webp file exists on disk
					if (ext !== '.webp' && existsSync(webpFile)) {
						const picture = {
							type: 'element',
							tagName: 'picture',
							properties: {},
							children: [
								{
									type: 'element',
									tagName: 'source',
									properties: { srcSet: webpSrc, type: 'image/webp' },
									children: []
								},
								node
							]
						};

						// Replace the img node with the picture node in parent's children
						if (parent && parent.children) {
							const idx = parent.children.indexOf(node);
							if (idx !== -1) {
								parent.children[idx] = picture;
							}
						}
					}
				}
				if (node.children) {
					// Iterate over a copy since we may mutate the array
					[...node.children].forEach((child) => visitImg(child, node));
				}
			};
			visitImg(tree, null);
		},
		// Normalize legacy migrated content so old image galleries and stray headings
		// do not flood the build with low-signal accessibility warnings.
		() => (tree) => {
			const isEmptyHeading = (node) => {
				if (node.type !== 'element') return false;
				if (!/^h[1-6]$/.test(node.tagName)) return false;
				return extractNodeText(node).trim().length === 0;
			};

			visitNodes(tree, null, (node, parent) => {
				if (node.type !== 'element') return;

				if (node.tagName === 'img') {
					node.properties = node.properties || {};
					if (typeof node.properties.alt !== 'string') {
						node.properties.alt = '';
					}
				}

				if (node.tagName === 'a') {
					node.properties = node.properties || {};
					const hasAccessibleName =
						typeof node.properties['aria-label'] === 'string' ||
						typeof node.properties['aria-labelledby'] === 'string' ||
						typeof node.properties.title === 'string' ||
						extractNodeText(node).trim().length > 0;

					if (!hasAccessibleName) {
						const imageNode = findFirstImage(node);
						if (imageNode) {
							const label = normalizeImageLabel(imageNode);
							node.properties['aria-label'] = `Open full-size ${label}`;
						} else {
							const parentText = extractNodeText(parent).trim();
							const href = typeof node.properties.href === 'string' ? node.properties.href : '';
							const fallbackLabel = parentText || href || 'Open link';
							node.properties['aria-label'] = fallbackLabel;
						}
					}
				}

				if (parent?.children && isEmptyHeading(node)) {
					parent.children = parent.children.filter((child) => child !== node);
				}
			});
		},
		// Style missing-image placeholder text as graceful notices
		() => (tree) => {
			const PLACEHOLDER_PATTERNS = [
				/image.*no longer available/i,
				/image.*lost to time/i,
				/photograph.*disappeared/i,
				/image.*unavailable/i,
				/image.*lost.*wordpress/i,
				/casualty.*wordpress/i,
				/wordpress.*decommission/i,
				/lost.*digital ether/i,
				/didn.*survive.*migration/i,
				/visual.*drifted away/i,
				/bits.*scattered.*wind/i,
				/gone with the wordpress/i,
				/server.*hosted.*gone dark/i,
				/digital entropy claimed/i,
				/once.*image.*memory.*url/i,
				/space once held an image/i,
				/wordpress cdn.*gone quiet/i,
				/void between wordpress/i,
			];

			const extractText = (node) => {
				if (node.type === 'text') return node.value || '';
				if (node.children) return node.children.map(extractText).join('');
				return '';
			};

			const visit = (node) => {
				if (node.type === 'element' && node.tagName === 'p' && node.children) {
					const textContent = extractText(node).trim();
					const isPlaceholder = PLACEHOLDER_PATTERNS.some((p) => p.test(textContent));
					if (isPlaceholder) {
						node.properties = node.properties || {};
						node.properties.className = [
							...(node.properties.className || []),
							'missing-image-notice'
						];
						node.properties.role = 'note';
						node.properties['aria-label'] = 'Image no longer available';
					}
				}
				if (node.children) node.children.forEach(visit);
			};
			visit(tree);
		},
		// Escape ALL curly braces in content to prevent Svelte parsing
		() => (tree) => {
			const escBraces = (s) => s.replace(/\{/g, '&#123;').replace(/\}/g, '&#125;');
			const visit = (node) => {
				if (node.type === 'text' && node.value) {
					node.value = escBraces(node.value);
				}
				if (node.type === 'raw' && node.value) {
					// Skip Svelte {@html} directives (e.g. from Shiki highlighter)
					if (!/^\s*\{@html\s/.test(node.value)) {
						node.value = escBraces(node.value);
					}
				}
				// Escape curly braces inside element attributes (e.g. href, src)
				if (node.type === 'element' && node.properties) {
					for (const [key, val] of Object.entries(node.properties)) {
						if (typeof val === 'string' && (val.includes('{') || val.includes('}'))) {
							node.properties[key] = escBraces(val);
						}
					}
				}
				if (node.children) {
					node.children.forEach(visit);
				}
			};
			visit(tree);
		}
	]
};

/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: ['.svelte', '.md', '.svx'],
	preprocess: [vitePreprocess(), mdsvex(mdsvexOptions)],
	compilerOptions: {
		runes: true
	},
	kit: {
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: '404.html',
			precompress: true,
			strict: false
		}),
		paths: {
			base: ''
		},
		prerender: {
			handleHttpError: 'warn',
			handleMissingId: 'warn'
		}
	}
};

export default config;
