#!/usr/bin/env node
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { format as formatWithPrettier } from 'prettier';
import type { SearchIndexEntry } from './lib/types.mts';
import { parseFrontmatter } from './lib/frontmatter.mts';

const POSTS_DIR = 'src/posts';
const OUTPUT = 'static/search-index.json';
const PUBLICATION_HOLDS_OUTPUT = 'static/blog-publication-holds.json';
const PUBLISHED_POST_LOADERS_OUTPUT = 'src/lib/data/blog-post-loaders.generated.ts';
const WORDS_PER_MINUTE = 230;

function computeReadingTime(text: string): number {
	const words = text.split(/\s+/).filter((w) => w.length > 0).length;
	return Math.max(1, Math.round(words / WORDS_PER_MINUTE));
}

async function main(): Promise<void> {
	const files = (await readdir(POSTS_DIR)).filter((f) => f.endsWith('.md'));
	const index: SearchIndexEntry[] = [];
	const publicationHolds: string[] = [];
	const publishedSourceFiles: string[] = [];

	for (const file of files) {
		const content = await readFile(join(POSTS_DIR, file), 'utf-8');
		const meta = parseFrontmatter(content);
		if (!meta) continue;

		const slug = (meta.slug as string) ?? file.replace('.md', '').replace(/^\d{4}-\d{2}-\d{2}-/, '');
		if (meta.published !== true) {
			if (meta.published === false) publicationHolds.push(slug);
			continue;
		}

		// Extract body excerpt (~150 chars of plain text)
		const body = content.replace(/^---[\s\S]*?---/, '');
		const plain = body
			.replace(/```[\s\S]*?```/g, '')
			.replace(/`[^`]*`/g, '')
			.replace(/<[^>]+>/g, '')
			.replace(/!\[[^\]]*\]\([^)]*\)/g, '')
			.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
			.replace(/[#*_~>|\\-]/g, '')
			.replace(/\s+/g, ' ')
			.trim();
		let body_excerpt = plain.slice(0, 150);
		if (plain.length > 150) {
			const lastSpace = body_excerpt.lastIndexOf(' ');
			body_excerpt = (lastSpace > 0 ? body_excerpt.slice(0, lastSpace) : body_excerpt) + '...';
		}

		const tagList = Array.isArray(meta.tags) ? (meta.tags as string[]) : [];
		const editorialTier = typeof meta.editorial_tier === 'string' ? meta.editorial_tier : undefined;

		const sourceFile = `/src/posts/${file}`;
		publishedSourceFiles.push(sourceFile);
		index.push({
			id: slug,
			title: String(meta.title ?? slug),
			description: String(meta.description ?? meta.excerpt ?? ''),
			tags: tagList.join(' '),
			tag_list: tagList,
			category: String(meta.category ?? ''),
			...(editorialTier
				? {
						editorial_tier: editorialTier,
						content_stratum: editorialTier,
					}
				: {}),
			slug,
			date: String(meta.date ?? ''),
			source_file: sourceFile,
			body_excerpt,
			published: Boolean(meta.published),
			reading_time: typeof meta.reading_time === 'number' ? meta.reading_time : computeReadingTime(plain),
			feature_image: typeof meta.feature_image === 'string' ? meta.feature_image : undefined,
			thumbnail_image: typeof meta.thumbnail_image === 'string' ? meta.thumbnail_image : undefined,
			featured: typeof meta.featured === 'boolean' ? meta.featured : undefined,
			author_slug: typeof meta.author_slug === 'string' ? meta.author_slug : undefined,
			original_url: typeof meta.original_url === 'string' ? meta.original_url : undefined,
			excerpt: typeof meta.excerpt === 'string' ? meta.excerpt : undefined,
		});
	}

	// Sort by date descending
	index.sort((a, b) => b.date.localeCompare(a.date));
	publicationHolds.sort((a, b) => a.localeCompare(b));
	publishedSourceFiles.sort((a, b) => a.localeCompare(b));
	const unsafeLoaderPath = publishedSourceFiles.find(
		(sourceFile) => !/^\/src\/posts\/[A-Za-z0-9._-]+\.md$/.test(sourceFile),
	);
	if (unsafeLoaderPath) {
		throw new Error(`Published post path cannot be emitted as an exact loader: ${unsafeLoaderPath}`);
	}

	const publishedPostLoadersSource = [
		'// Generated by scripts/generate-search-index.mts. Do not edit by hand.',
		'export const publishedPostLoaders = import.meta.glob([',
		...publishedSourceFiles.map((sourceFile) => `\t${JSON.stringify(sourceFile)},`),
		']);',
		'',
	].join('\n');
	const publishedPostLoaders = await formatWithPrettier(publishedPostLoadersSource, {
		parser: 'typescript',
		printWidth: 120,
		singleQuote: true,
		trailingComma: 'all',
		useTabs: true,
	});

	await Promise.all([
		writeFile(OUTPUT, JSON.stringify(index), 'utf-8'),
		writeFile(PUBLICATION_HOLDS_OUTPUT, JSON.stringify(publicationHolds), 'utf-8'),
		writeFile(PUBLISHED_POST_LOADERS_OUTPUT, publishedPostLoaders, 'utf-8'),
	]);
	console.log(`Search index: ${index.length} posts -> ${OUTPUT}`);
	console.log(`Publication holds: ${publicationHolds.length} slugs -> ${PUBLICATION_HOLDS_OUTPUT}`);
	console.log(`Published post loaders: ${publishedSourceFiles.length} modules -> ${PUBLISHED_POST_LOADERS_OUTPUT}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
